title: Yongjeong Kim
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Yongjeong Kim # add your name
author-img: david-freeman.jpg # add your photo
about-author: Sc.M student at Brown University # add description
social-github: CSEYJ # add your Github handle
social-linkedin: yongjeong-kim-9b6199155/ # add your Linkedin handle
social-email: yongjeong_kim@brown.edu # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
